### ISSUE TITLE
Automatic generation of Solidity counterpart of machine::reset_uarch_state() from C++ code

### ISSUE THREAD

**Issue by diegonehab** [cartesi/machine-emulator#100]
## Context

The Solidity version of `machine::step_uarch()` is automatically generated from C++ code.
We should do the same with `machine::reset_uarch_state()`, including hardcoding of necessary hashes for large accesses, such as the one used to replace uarch RAM.

**Comment by GCdePaula** [comment]
I'm not sure I understand!

> The Solidity version of `machine::step_uarch()` is automatically generated from C++ code.

Yeah, as I understand it's mostly generated from C++ (specifically, the `uarch` step), plus a tiny Solidity template.

> We should do the same with `machine::reset_uarch_state()`

How? The way I understood it, there would be a hand written Solidity file containing the "surgery" logic, which would import a file with the constants (mekleized pristine `uarch` state). This file with constants would be generated from a build artifact of the C++ big-architecture step.

**Comment by diegonehab** [comment]
At the moment, the `machine::reset_uarch_state()` method clears `uarch.cycle`, sets `uarch.pc` to the start of `uarch.ram`, clears the `uarch.halted_flag`, sets all `uarch.x[*]` to 0, and restores the entirety of `uarch.ram` to its initial state. At some point, these things will be all moved to live in the same Merkle tree node, so that it will be possible to accomplish all this with a single surgery that replaces that entire node with the single "large write" access that appears in the log returned by `machine::reset_uarch_state()`. For that, we would only need to generate the hash of the node that is being replaced to appear in some file. To do that, all we need is to ask `cartesi-machine` to produce a proof for that node and use `jq` to select the target hash. Or some other trick.

The first implementation, however, will likely include all these steps as distinct operations. Since they will appear in the log as distinct operations, it makes sense to write the code for `machine::reset_uarch_state()` in a way that allows those steps to be transformed to their Solidity equivalents in a similar way to how `machine::step_uarch()` does, and treat these "large write" operations (perhaps one for  the entire x-register file and another for the RAM) as if they were simply writing constants somewhere (the constant being the hash of the node).
