### ISSUE TITLE
Make machine::reset_uarch_state() use a single access in the access log

### ISSUE THREAD

**Issue by diegonehab** [cartesi/machine-emulator#101]
## Context

Currently, `machine::reset_uarch_state()` performs a variety of independent operations. It resets `uarch.pc`, `uarch.cycle`, `uarch.halt_flag`, all `uarch.x` registers, and the entire RAM contents. By positioning all these data under the same node of a Merkle tree, we can compute their initial hash and log a single write that replaces whatever dirty node might exist in the machine at the moment with its initial value.

## Possible solutions

We do not need to put all these data inside the same PMA. All we have to do is make sure is that they are adjacent enough so that a single Merkle tree node covers all this data an no independent unrelated data. In other words, the data must be inside a memory region with a power-of-two size, and aligned to that size. There could be gaps, but those gaps cannot be filled with data that that would be unduly overwritten by `machine::reset_uarch_state()`.

**Comment by vfusco** [comment]
closed by #141
