### ISSUE TITLE
Exit code should be non zero for kernel panics

### ISSUE THREAD

**Issue by edubart** [cartesi/machine-emulator#144]
## Context

Currently if the kernel panics, the `cartesi-machine` command exit status will be 0, this makes some of our tests in CI to assume that it passed.

**Comment by mpolitzer** [comment]
done in https://github.com/cartesi/linux/commit/9c1659c2edd58fb0484b660cde41f5ff4200cf17 and merged with https://github.com/cartesi/image-kernel/pull/22
