### ISSUE TITLE
Homebrew build instructions are not working

### ISSUE THREAD

**Issue by tuler** [cartesi/machine-emulator#145]
## Context

For a developer who uses macOS, but not work with C or C++, building the cartesi machine is still a challenge.
I've followed the README instructions for homebrew and it did not work.

## Possible solutions

I think we should have a CI build process using homebrew, following the README instructions, to make it works on a clean environment.

## Definition of Done

- [ ] CI of a build with homebrew passing

**Comment by vfusco** [comment]
fixed by #149
