### ISSUE TITLE
`make dep` fails if `third-party/downloads/` directory exists (even if it is empty)

### ISSUE THREAD

**Issue by mpolitzer** [cartesi/machine-emulator#157]
## Context

> What is the bug that you are experiencing?

Rebuilding the emulator fails with certain conditions.

> Why is this bug relevant?

This is relevant during the development process and requires manual intervention besides `make` calls

## Expected behavior

`make dep` should download the file: `third-party/downloads/7.12.tar.gz`

## Actual behavior

```
make dep                                                                                                                                                               
tar -C third-party -xzf third-party/downloads/7.12.tar.gz mongoose-7.12/mongoose.c mongoose-7.12/mongoose.h                                                                                                             
tar (child): third-party/downloads/7.12.tar.gz: Cannot open: No such file or directory                                                                                                                                  
tar (child): Error is not recoverable: exiting now                                                                                                                                                                      
tar: Child returned status 2                                                                                                                                                                                            
tar: Error is not recoverable: exiting now                                                                                                                                                                              
make: *** [Makefile:171: third-party/mongoose-7.12] Error 2                                                                                                                                                             
```

## Steps to reproduce

create the `third-party/downloads/` directory before `make dep`

## Environment

Please describe the environment where the bug happens.

Include the following (when applicable and/or relevant):
- Emulator version: [latest] 88bf5749df883569ae361b4f4e66851259f0a0d7

## Possible solutions

Is there any workaround for the issue? (This may help others experiencing the same issue.)
Manually removing the `third-party/downloads/` directory solved the issue.

Can you offer any hint on how to solve the issue?
`make depclean` should remove the `third-party/downloads/` directory

**Comment by edubart** [comment]
`make dep` and `make downloads` will go away with https://github.com/cartesi/machine-emulator/pull/240
