### ISSUE TITLE
Add TLB implementation to log off-chain and follow implementation on-chain

### ISSUE THREAD

**Issue by diegonehab** [cartesi/machine-emulator#21]
At the moment, the TLB is implemented as an off-chain optimization to machine-emulator, but not on-chain in machine-solidity-step. This works for conforming software that executes a fence.vma instruction whenever the virtual memory map is changed. This is the way to ensure deterministic behavior according to the RISC-V specification. However, an ill-formed or malicious program can mess with the virtual memory map and then fail to execute fence.vma, either by accident or on purpose. This would cause the TLB to be outdated relative to the virtual memory map, and thus lead to mismatching behavior on- and off-chain.

To be on the safe side and prevent this potential source of non-determinism, we have decided to have matching TLB implementations on- and off-chain. This will require changes to the machine-emulator implementation, so it becomes possible to efficiently implement the TLB on-chain. Then, the state accesses related to the TLB will have to be logged. Once these changes have been made, a matching TLB implementation will be added to the on-chain code in machine-solidity-step. 

This issue will track the progress of these changes.

See cartesi/machine-solidity-step#18.

**Comment by edubart** [comment]
Since the microarchitecture, the TLB is implemented in the big emulator and there is no need to be implemented on-chain, therefore this issue is not anymore.
