### ISSUE TITLE
Include generated C files in source tarball

### ISSUE THREAD

**Issue by edubart** [cartesi/machine-emulator#233]
# Context

To make easier to distribute sources, we should include a few generated files in the source tarball:

- `machine-c-version.h`
- `uarch-pristine-ram.c`
- `uarch-pristine-hash.c`

**Comment by mpolitzer** [comment]
Consider distributing those as a `.patch` instead.
Should make it easy for distributions to use and not complicate the source tarball generation either.

**Comment by edubart** [comment]
This was done by https://github.com/cartesi/machine-emulator/pull/243
