### ISSUE TITLE
Brew formula

### ISSUE THREAD

**Issue by tuler** [cartesi/machine-emulator#271]
## Context

[Homebrew](https://brew.sh) is one of the two most popular package managers for macOS.
It's a very convenient tool for a lot of users and developers.

It would be great to have a brew [formula](https://docs.brew.sh/Adding-Software-to-Homebrew#formulae) to install cartesi-machine from source.

```shell
brew install cartesi-machine
```

## Possible solutions

The machine-emulator is already compilable with dependencies coming from brew.
But this issue is about taking one step further and providing a brew formula to install the machine-emulator products from source: binaries, include files, libraries.

Brew has a particular organization, typically something like:

```
"$(brew --prefix)"/Cellar/cartesi-machine/0.18.1/
   README.md
   LICENSE
   bin/
   include/
   lib/
   share/
```

And that is symliked to:
```
"$(brew --prefix)"/bin
"$(brew --prefix)"/include
"$(brew --prefix)"/lib
(...)
```

One could argue that it's possible to delegate this task to a third-party developer not part of the machine-emulator team. But I believe there will be changes to the Makefile to make it more compatible with the brew build system.

ps: after the formula works it's also possible to provide pre-compiled binaries through [brew bottles](https://docs.brew.sh/Bottles).

## Definition of Done

- [ ] `brew install cartesi-machine`

**Comment by tuler** [comment]
@alexmikhalevich stabbed this at https://github.com/alexmikhalevich/homebrew-cartesi/
need to see how to update to latest emulator version

**Comment by tuler** [comment]
Trying this starting from @alexmikhalevich work
https://github.com/cartesi/homebrew-tap/pull/1

**Comment by tuler** [comment]
Ready for review at https://github.com/cartesi/homebrew-tap/pull/4

**Comment by edubart** [comment]
> But I believe there will be changes to the Makefile to make it more compatible with the brew build system.

Alex upstreamed the required Brew changes, so looks like there was no need for Makefile patches :)

**Comment by tuler** [comment]
```
brew tap cartesi/tap
brew install cartesi-machine
```

**Comment by tuler** [comment]
https://github.com/cartesi/homebrew-tap/issues/5
