### ISSUE TITLE
Add version command line option

### ISSUE THREAD

**Issue by edubart** [cartesi/machine-emulator#56]
## Context

Currently there is no way to know the installed emulator version via the command line. We should support this so a user can identify which version of the emulator he is running, this also helps us to identify which version exactly an user is running when he reports an issue (because we can just ask the `cartesi-machine --version` output). This may also be used by other tools that depend on cartesi machine (such as Sunodo), to make sure it's compatible with the cartesi machine version before invoking it.

## Possible solutions

For releases the `--version` option could output something like the following:
```
$ cartesi-machine --version
Cartesi machine v0.11.0
Build date: 2022/12/31
Git commit: 11e12534c35fb6c5186270466b9c148cc008d921
Semver: 0.12.0
```

And for development versions:

```
$ cartesi-machine --version
Cartesi machine v0.11.0-dev
Build date: 2022/12/31
Git commit: 11e12534c35fb6c5186270466b9c148cc008d921
Semver: 0.12.0-dev+11e12534c35fb
```

The above output is just an idea, what exactly to output is up to debate, but it should output at least the current release tag. 
It would also be helpful to show the emulator version in the help output.

We could also have a `--semver` command option to be easy to use with other tools, outputting just its semantic version. For example:

```
$ cartesi-machine --semver
0.12.0
```

Detecting emulator version from inside a virtual machine may also be helpful for dapps to make sure it's running inside a compatible cartesi machine. We could expose the emulator semver in `mimpid` CSR using the following scheme:

- v0.11.0 => mimpid=000011000
- v2.12.9 => mimpid=002012009
- v123.456.789 => mimpid=123456789

This way to could make a tool that reads `mimpid` and detects the emulator version without the need to maintain a map for `marchid` CSR.

**Comment by tuler** [comment]
Some tools even provide a json output.
Try `docker version --format json`
