### ISSUE TITLE
Support for running machines in the browser with WebAssembly

### ISSUE THREAD

**Issue by edubart** [cartesi/machine-emulator#59]
## Context

We can add support for the whole Cartesi Machine C API to WebAssembly, especially using the [Emscripten](https://emscripten.org/) toolchain. This will allow dapp developers to use the Cartesi Machine inside a WebAssembly environment (such as browsers), opening possibilities to run a Cartesi Machine not only on the blockchain side for proofs, but also in client side web pages for dapps that needs do deterministic computations that matches the computations done in blockchain side.

## Possible solutions

We don't have to edit much of the emulator code to do this, this has been tested and the emulator works fine with the Emscripten toolchain. It's mostly a makefile and dependency problem.

We should try to minimize the amount of external dependencies (such as Crypto++, boost, b64, etc), possibly bundling them inside the emulator or when not possible, by providing a repository for WebAssembly third-party dependencies.

When finished, we could provide a web page where people could interact and experiment with a serverless emulated Linux fully running in the browser, very similar to [WebVM](https://webvm.io/) just to show off emulator capabilities.

**Comment by stskeeps** [comment]
Also interesting could see if Emscripten could be replaced with WASI interfaces

**Comment by edubart** [comment]
> Also interesting could see if Emscripten could be replaced with WASI interfaces, such as building towards https://github.com/WebAssembly/wasi-sdk

In general Emscripten supports more APIs and features than WASI-SDK, therefore as a first milestone getting to work with its toolchain should be easier. After we get things to work with Emscripten, indeed it would be interesting to investigate what should be done to also support the WASI SDK toolchain, I imagine we may have some APIs missing. With WASI SDK and a WASI runtime in the host, it would be possible to provide portable cross platform `.wasm` binaries of the cartesi machine, just requiring a WASI runtime in the host, and that is interesting. It would allow for example to run the cartesi machine in more platforms than we support without the need to explicitly support them in our sources, like Windows. In fact any platform that has a WASI runtime will be able to run it.
