### ISSUE TITLE
Separate addresses of big arch and uarch shadow states

### ISSUE THREAD

**Issue by edubart** [cartesi/machine-emulator#64]
## Context

It would be best to completely separate the addresses of the uarch and big arch states. This is because we will want to reset the uarch state without touching anything in the big arch state. If they are close, we will need many independent Merkle tree operations to obtain the corresponding state hash. If they are entirely separate, we will be able to reset the uarch state with a single "bubble up" operation.

Furthermore we should fix uarch state in an address range where any removal or addition of big arch CSRs doesn't offsets uarch addresses, because this typically changes any tests which have their addresses as a hard constant.

## Possible solutions

We could move uarch state before all big arch CSRs, or as suggested by @diegonehab we could move them to the end of the machine's physical address space.

We should also think of a solution for exposing uarch CSRs to the machine solidity step (issue https://github.com/cartesi/machine-solidity-step/issues/42) when doing this.

**Comment by diegonehab** [comment]
This issue is now related to #101

**Comment by vfusco** [comment]
closed by #141
