### ISSUE TITLE
Embed microarchitecture binary in big emulator

### ISSUE THREAD

**Issue by edubart** [cartesi/machine-emulator#68]
## Context

Currently we compile `uarch-ram.bin` using a RISC-V toolchain and then explicitly load it when invoking the cartesi machine. However we could and I think we should load this implicitly, by embedding `uarch-ram.bin` binary into the big emulator, and load its PMA automatically for all cases. This will make it harder for anyone to use wrong `uarch-ram.bin` with an incompatible emulator version and also make uarch easier to use.

## Possible solutions

To make this we need to embed files into C++ programs, there are couple of ways to do this:

Using `ld` to convert any file to an object file:
1. Do `ld -r -b binary -o uarch-ram.bin.o uarch-ram.bin`, this will generate a .o with its data.
2. Do `objdump -x uarch-ram.bin.o`, just to confirm the data symbol names.
3. Import the symbols with:
```
extern "C" char _binary_uarch_ram_bin_start[];
extern "C" char _binary_uarch_ram_bin_end[];
```

Using the tool `xxd -i`:

Simply do `xxd -i uarch-ram.bin > uarch-ram.bin.h` and use it.
I think this way is more friendly to work with any compiler, but requires `xxd`, I prefer this way.

## Definition of Done

- [ ] `run_uarch()` should be usable without the need of any user-provided configuration.
- [ ] `uarch-ram.bin` and `uarch-ram.bin.h` artifacts should be provided for download in CI for releases, this will help packaging the emulator for any Linux distribution without the need to always have to recompile `uarch-ram.bin`.

**Comment by diegonehab** [comment]
Should we use `xxd -i ` to embed the `jsonrpc-discover.json` as well? @edubart

**Comment by diegonehab** [comment]
What should we do with the `uarch.ram` configuration in the `machine_config`?

**Comment by edubart** [comment]
> Should we use xxd -i  to embed the jsonrpc-discover.json as well? @edubart 

If we start depending on `xxd` to build anyway, we might as well do this.

> What should we do with the uarch.ram configuration in the machine_config?

Could we leave it there, like we are doing with ROM? Whereas the default empty will start to actually fill with the embedded uarch RAM instead, which could be useful for rare debugging or developing purposes. But is that kind of option that people should not be using.

**Comment by diegonehab** [comment]
I don’t know. I feel like it’s almost like a .o in the executable. The emulator is incomplete without it. I would therefore remove the configuration option. Code becomes simpler. Unless you see some crazy debug reason for it to be there.
