### ISSUE TITLE
Machine config usability enhancements for testing

### ISSUE THREAD

**Issue by edubart** [cartesi/machine-emulator#69]
## Context

There are some inflexibilities in the Lua configuration that makes more boilerplate for us to create tests. Like the impossibility of creating a machine with an empty rom (we have to do tricks to create empty files), and the requirement of always needing to get flash drive length (this could be auto detected).

## Definition of Done

- [x] Support creating a machine without a ROM image filename. ROM could still be overwritten with a memory write.
- [x] Allow omitting length from flash drive configs, instead fill this automatically by getting the file size.

**Comment by diegonehab** [comment]
Isn't this merged already, @edubart ?
