### ISSUE TITLE
Change base image to `debian`

### ISSUE THREAD

**Issue by mpolitzer** [cartesi/machine-emulator#74]
## Context

There is a move to the `debian` distribution in docker images across the `org`.
We should do it on the emulator as well.

## Dependencies

- [x] We need a debian `cartesi/toolchain` image with the uarch cross compiler.
- [x] Update `copyright`, NEWS and changelog.gz on the `make debian` target.

**Comment by edubart** [comment]
Debian bookworm is about to released next week, we should also consider using it, so we have more up to date toolchain and dependencies.
