### ISSUE TITLE
Update machine::reset_uarch_state() for implementation in Solidity

### ISSUE THREAD

**Issue by diegonehab** [cartesi/machine-emulator#97]
## Context

Implementation of arbitration is reaching a point where it will need to use the `machine::reset_uarch_state()` method. More importantly, this method will be needed in Solidity as well. In order to make this implementation as simple as possible, we should reuse as many existing concepts as possible. A good alternative is to make `machine::reset_uarch_state()` behave as close as possible to the way in which `machine::step_uarch()` behaves. This epic describes the steps towards such a solution.

## Subtasks

-  #98;
-  #99;
- #100;
- #101.

**Comment by diegonehab** [comment]
@GCdePaula @mpernambuco @stephenctw Please comment on the epic and related issues.

**Comment by vfusco** [comment]
closed by #141
