### ISSUE TITLE
Make machine::reset_uarch_state() return an access_log, just like machine::step_uarch() does

### ISSUE THREAD

**Issue by diegonehab** [cartesi/machine-emulator#99]
## Context

In order to enable the automatic generation of `machine::reset_uarch_state()` in Solidity in a similar way to how `machine::step_uarch()` is automatically generated, we need to make `machine::reset_uarch_state()` produce an `access_log` that can be consumed by the Solidity implementation.

The only notable difference is that the `machine::reset_uarch_state()` makes at least one _large_ access to restore the entire contents of its RAM with a single operation. Issue #98 explains how `access_log`s already have support for such large accesses.

**Comment by vfusco** [comment]
closed by #141
